# GENERATED by aganitha-ie-skill-creator. Never hand-edit.
#
# /// script
# requires-python = ">=3.11"
# dependencies = []
#
# Requires the aganitha-ie-people CLI and yt-dlp on PATH — see SETUP.md.
# ///
"""Stage 1-2: identity-resolved experts for a disease, and the videos naming them.

  uv run tools/candidates.py --search-name "obstructive sleep apnea syndrome" \
      --out candidates.json --videos videos.json

Emits experts with a CANONICAL name spelling. That spelling is the reason this
stage exists: the consumer groups records by kol_name, so one person under two
spellings renders as two cards, and auto-captions cannot be trusted to spell a
name. Never merges on surname alone; never splits on a differing affiliation.
"""
from __future__ import annotations

import argparse, json, os, re, shutil, subprocess, sys

TUNABLES: dict[str, int] = {
    # Papers examined per literature query.
    "DBTIPS_KOL_PAPERS": 600,
    # Candidates returned per aganitha-ie-people command.
    "DBTIPS_KOL_MENTIONS": 600,
    # YouTube results per expert. The upstream default of 8 truncates a
    # well-covered expert silently.
    "DBTIPS_KOL_VIDEO_HITS": 25,
    # Trials examined when building the trial-publication bridge.
    "DBTIPS_KOL_BRIDGE_TRIALS": 300,
    # Minimum number of INDEPENDENT sources that must confirm a person before they
    # are carried into the video stage. This is the real gate: 2 means the person
    # appears in at least two of trials / guidelines / authoritative papers /
    # grants. A fixed-size shortlist pads a thin field with noise and truncates a
    # deep one -- both failures the skill's rank-by-breadth step exists to prevent.
    "DBTIPS_KOL_MIN_BREADTH": 2,
    # Safety ceiling only, NOT a target. 0 means no ceiling: take everyone who
    # clears MIN_BREADTH and report how many that was.
    "DBTIPS_KOL_SHORTLIST": 0,
    # Seconds any subprocess may run.
    "DBTIPS_KOL_SUBPROCESS_TIMEOUT": 180,
}

CRED = {"md","phd","mph","ms","msc","do","dds","mbbs","frcp","mb","chb","dphil","rn","facp","fccp","faasm"}
ACCENTS = "-éèêüöáíóúñ"


def tunable(name: str) -> int:
    raw = os.getenv(name)
    if raw in (None, ""):
        return TUNABLES[name]
    try:
        v = int(raw)
    except ValueError:
        sys.exit(f"error: {name}={raw!r} is not an integer.")
    if v <= 0:
        sys.exit(f"error: {name}={v} must be positive.")
    return v


def run_json(args: list[str], timeout: int) -> dict:
    try:
        r = subprocess.run(args, capture_output=True, text=True, timeout=timeout, check=False)
    except subprocess.TimeoutExpired:
        sys.exit(f"error: `{' '.join(args[:2])}` exceeded DBTIPS_KOL_SUBPROCESS_TIMEOUT. "
                 f"Tool failure, not an empty result.")
    if r.returncode != 0 or not r.stdout.strip():
        return {}
    try:
        return json.loads(r.stdout)
    except json.JSONDecodeError:
        return {}


def tokens(name: str) -> list[str]:
    n = re.sub(r"\b(Professor|Prof|Pr|Dr)\b", "", name)
    n = re.sub(r"[.,;]+", " ", n)
    t = [x for x in n.split() if x.strip() and x.lower().strip(".") not in CRED]
    return [x for x in t if len(x.strip(".")) > 1]


def canonical(variants: set[str]) -> str | None:
    """One display name per person: 'Firstname Lastname'. Prefers the spelling
    carrying diacritics or a hyphen, because that is the person's own."""
    for v in sorted(variants, key=lambda s: (-sum(c in s for c in ACCENTS), len(s))):
        t = tokens(v)
        if len(t) >= 2:
            return f"{t[0]} {t[-1]}"
    return None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--search-name", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--videos", required=True)
    a = ap.parse_args()

    resolved = {k: tunable(k) for k in TUNABLES}
    missing = [t for t in ("aganitha-ie-people", "yt-dlp") if not shutil.which(t)]
    if missing:
        sys.exit(f"error: missing required tool(s): {', '.join(missing)}. See SETUP.md. "
                 f"A missing tool changes the plan; it never silently degrades the run.")

    env = dict(os.environ,
               KOL_PAPERS=str(resolved["DBTIPS_KOL_PAPERS"]),
               KOL_MENTIONS=str(resolved["DBTIPS_KOL_MENTIONS"]),
               KOL_VIDEO_HITS=str(resolved["DBTIPS_KOL_VIDEO_HITS"]),
               KOL_BRIDGE_TRIALS=str(resolved["DBTIPS_KOL_BRIDGE_TRIALS"]))
    os.environ.update(env)
    T = resolved["DBTIPS_KOL_SUBPROCESS_TIMEOUT"]
    disease = a.search_name

    resolved_disease = run_json(["aganitha-ie-people", "resolve-disease", disease], T)
    conditions = [c for c in (resolved_disease.get("use_as_conditions") or [disease])]
    notes = list(resolved_disease.get("notes") or [])

    cond_args: list[str] = []
    for c in conditions[: 8]:
        cond_args += ["--condition", c]

    trials = run_json(["aganitha-ie-people", "trial-people", *cond_args], T)
    # Guidelines are queried on BOTH the plain term and the resolved MeSH heading
    # and unioned. Trusting the heading alone can return zero where the plain
    # term returns hundreds, losing the whole guideline signal silently.
    guides: dict = {"candidates": []}
    for term in {disease, *conditions[:3]}:
        g = run_json(["aganitha-ie-people", "literature-people", "--condition", term, "--guidelines-only"], T)
        guides["candidates"].extend(g.get("candidates") or [])
    auth = run_json(["aganitha-ie-people", "literature-people", "--condition", disease, "--authority-only"], T)
    grants = run_json(["aganitha-ie-people", "grants", "--condition", disease], T)
    bridge = run_json(["aganitha-ie-people", "bridge", *cond_args[:4]], T)

    def idx(d):
        out: dict[str, dict] = {}
        for c in (d.get("candidates") or []):
            out.setdefault(c["name_key"], c)
        return out
    tp, gp, au, gr = idx(trials), idx(guides), idx(auth), idx(grants)
    br = {b["name_key"]: b for b in (bridge.get("bridges") or [])}

    people = []
    for k in set(tp) | set(gp) | set(au) | set(gr):
        nt = tp.get(k, {}).get("trial_count", 0)
        ng = len(gp.get(k, {}).get("guideline_papers") or [])
        na = au.get(k, {}).get("paper_count", 0)
        ngr = gr.get(k, {}).get("project_count", 0)
        breadth = sum(map(bool, (nt, ng, na, ngr)))
        variants: set[str] = set()
        for src in (tp, gp, au, gr):
            variants.update(src.get(k, {}).get("surface_forms") or [])
        if k in br:
            variants.update((br[k].get("registry_forms") or []) + (br[k].get("literature_forms") or []))
        name = canonical(variants)
        if not name:
            continue
        # Affiliation: the author's own paper string first, the registry second.
        aff = None
        for src in (gp, au):
            for s in (src.get(k, {}).get("affiliations") or []):
                if s:
                    aff = s.strip(); break
            if aff: break
        if not aff:
            cands = tp.get(k, {}).get("affiliations") or []
            good = [x for x in cands if any(w in x.lower() for w in
                    ("universit","hospital","center","centre","clinic","institut","school","college"))]
            pool = good or cands
            if pool:
                aff = sorted(pool, key=lambda x: (abs(len(x) - 40), x))[0]
        people.append({
            "name_key": k, "name": name, "name_variants": sorted(variants),
            "affiliation": aff, "bridged": k in br, "breadth": breadth,
            "signals": {"trials": nt, "guidelines": ng, "papers": na, "grants": ngr},
            "pmids": sorted({*(gp.get(k, {}).get("pmids") or []),
                             *(au.get(k, {}).get("pmids") or []),
                             *((br.get(k) or {}).get("pmids") or [])})[:60],
        })
    # Tie-break on actual signal strength, never on name. Falling through to name
    # made ranks 22+ alphabetical in an earlier run, filling a quarter of the
    # shortlist with people who had no media presence and pulling in unrelated
    # namesakes (a disc-golf player, a food reviewer) as false positives.
    def weight(p):
        s = p["signals"]
        return s["trials"] * 3 + s["guidelines"] * 2 + s["grants"] * 2 + s["papers"]
    for p in people:
        p["signal_weight"] = weight(p)
    people.sort(key=lambda p: (-p["breadth"], not p["bridged"], -p["signal_weight"], p["name"]))

    min_breadth = resolved["DBTIPS_KOL_MIN_BREADTH"]
    qualified = [p for p in people if p["breadth"] >= min_breadth]
    ceiling = resolved["DBTIPS_KOL_SHORTLIST"]
    shortlist = qualified[:ceiling] if ceiling else qualified
    truncated = bool(ceiling) and len(qualified) > ceiling

    # Stage 2 — videos, strict on BOTH given and family name. A shared surname
    # is not a match: it attributes one person's talk to another.
    videos = []
    for p in shortlist:
        v = run_json(["aganitha-ie-people", "videos", "--name", p["name"], "--topic", disease], T)
        first, last = p["name"].lower().split()[0], p["name"].lower().split()[-1]
        for c in (v.get("candidates") or []):
            blob = f"{c.get('title','')} {c.get('channel','')}".lower()
            if not (re.search(rf"\b{re.escape(first)}\b", blob) and re.search(rf"\b{re.escape(last)}\b", blob)):
                continue
            m = re.search(r"v=([\w-]+)", c.get("url", ""))
            if m:
                videos.append({"video_id": m.group(1), "name_key": p["name_key"], "kol_name": p["name"]})

    with open(a.out, "w", encoding="utf-8") as fh:
        json.dump({"search_name": disease, "resolve_disease_notes": notes,
                   "tunables_resolved": resolved,
                   "people_ranked": len(people),
                   "qualified_at_min_breadth": len(qualified),
                   "shortlisted": len(shortlist),
                   "truncated_by_ceiling": truncated,
                   "breadth_distribution": {str(b): sum(1 for p in people if p["breadth"] == b)
                                            for b in sorted({p["breadth"] for p in people}, reverse=True)},
                   "experts": shortlist}, fh, ensure_ascii=False, indent=1)
    with open(a.videos, "w", encoding="utf-8") as fh:
        json.dump(videos, fh, ensure_ascii=False, indent=1)
    print(f"experts: {len(shortlist)} shortlisted ({len(qualified)} qualified at "
          f"breadth>={min_breadth}, {len(people)} ranked) | videos: {len(videos)} "
          f"| distinct: {len({v['video_id'] for v in videos})}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
