# GENERATED by aganitha-ie-skill-creator. Never hand-edit.
#
# /// script
# requires-python = ">=3.11"
# dependencies = ["baml-py>=0.214.0"]
#
# Requires yt-dlp on PATH — see SETUP.md.
# ///
"""Run ONE video through the generated BAML function and emit JSON.

  uv run tools/extract.py <video_id> --search-name "<disease>" \
      --candidates candidates.json [--run-context '{...}']

Writes KolVideoExtraction JSON to stdout. Exits non-zero on any failure: a
partial or absent extraction reported as success is the failure mode the
guidelines exist to prevent.
"""
from __future__ import annotations

import argparse, json, os, re, shutil, subprocess, sys, tempfile
from pathlib import Path

SKILL_ROOT = Path(__file__).resolve().parent.parent
GUIDELINES = SKILL_ROOT / "references" / "guidelines.md"
sys.path.insert(0, str(SKILL_ROOT))

# Every number that changes what a run does or how long it may take is
# configuration, not a literal. Defaults make the tool work with nothing set;
# a bad value stops the run rather than reverting silently. The resolved values
# ship with the result, because a run is only interpretable next to its limits.
TUNABLES: dict[str, int] = {
    # Seconds any yt-dlp call may run. A throttled or geo-blocked video can hang
    # indefinitely, and a hung extraction is worse than a failed one: it reports
    # nothing at all, forever.
    "DBTIPS_KOL_SUBPROCESS_TIMEOUT": 120,
    # Characters of transcript passed to the model. Sized so a long grand-rounds
    # talk still fits; raise it rather than accept a silent truncation.
    # Segment size sent per model call. The transcript is never truncated: one
    # longer than this is split into ordered segments and each is analysed with
    # the running extraction carried forward.
    "DBTIPS_KOL_CHUNK_CHARS": 24000,
    # Characters repeated between consecutive segments so a stance that straddles
    # a boundary survives the split.
    "DBTIPS_KOL_CHUNK_OVERLAP": 1500,
    # Hard ceiling on segments per video. A malformed caption file can otherwise
    # spend an unbounded number of model calls.
    "DBTIPS_KOL_MAX_CHUNKS": 12,
    # Characters of video description passed as metadata.
    "DBTIPS_KOL_DESCRIPTION_CHARS": 4000,
}


def tunable(name: str) -> int:
    raw = os.getenv(name)
    if raw is None or raw == "":
        return TUNABLES[name]
    try:
        value = int(raw)
    except ValueError:
        sys.exit(f"error: {name}={raw!r} is not an integer. Unset it or give a whole number.")
    if value <= 0:
        sys.exit(f"error: {name}={value} must be positive.")
    return value


def require_tools(*names: str) -> tuple[list[str], list[str]]:
    """[[verify-tools-before-running]] — a miss changes the plan, never degrades silently."""
    found = [n for n in names if shutil.which(n)]
    missing = [n for n in names if not shutil.which(n)]
    return found, missing


def _run(cmd: list[str], timeout: int) -> subprocess.CompletedProcess:
    try:
        return subprocess.run(cmd, capture_output=True, text=True, timeout=timeout, check=False)
    except subprocess.TimeoutExpired:
        sys.exit(f"error: `{cmd[0]}` exceeded DBTIPS_KOL_SUBPROCESS_TIMEOUT. "
                 f"This is a tool failure, not an absent transcript. Raise the variable and retry.")


def fetch_metadata(video_id: str, timeout: int) -> dict:
    url = f"https://www.youtube.com/watch?v={video_id}"   # bare ids starting with '-' parse as flags
    r = _run(["yt-dlp", "--skip-download", "--no-warnings", "--dump-json", url], timeout)
    if r.returncode != 0 or not r.stdout.strip():
        sys.exit(f"error: could not read metadata for {video_id}: {r.stderr.strip()[:300]}")
    d = json.loads(r.stdout.splitlines()[0])
    up = d.get("upload_date") or ""
    return {
        "video_id": d.get("id"),
        "title": d.get("title"),
        "description": (d.get("description") or "")[: tunable("DBTIPS_KOL_DESCRIPTION_CHARS")],
        "channel_name": d.get("channel") or d.get("uploader"),
        "published_date": f"{up[:4]}-{up[4:6]}-{up[6:]}" if len(up) == 8 else None,
        "view_count": str(d["view_count"]) if d.get("view_count") is not None else None,
        "duration_seconds": str(d["duration"]) if d.get("duration") is not None else None,
    }


def fetch_transcript(video_id: str, timeout: int) -> tuple[str, bool]:
    """Returns (text, available, tool_note). Empty-with-available-False is a tool
    outcome, not a finding about the video — [[tool-failure-is-not-a-finding]].
    tool_note carries stderr so the caller can tell a throttle from an absence."""
    url = f"https://www.youtube.com/watch?v={video_id}"
    with tempfile.TemporaryDirectory() as td:
        r = _run(["yt-dlp", "--skip-download", "--write-auto-subs", "--write-subs",
                  "--sub-lang", "en.*", "--sub-format", "vtt", "--no-warnings",
                  "-o", str(Path(td) / "%(id)s.%(ext)s"), url], timeout)
        vtts = sorted(Path(td).glob("*.vtt"))
        if not vtts:
            return "", False, (r.stderr or "").strip()[:300] if r else "subprocess timeout"
        # prefer a human track over an auto one; auto-captions mistranscribe names
        vtts.sort(key=lambda p: "orig" in p.name)
        seen, out = set(), []
        for line in vtts[0].read_text(encoding="utf-8", errors="ignore").splitlines():
            line = line.strip()
            if not line or "-->" in line or line.startswith(("WEBVTT", "Kind:", "Language:", "NOTE")):
                continue
            line = re.sub(r"<[^>]+>", "", line).strip()
            if line and line not in seen:
                seen.add(line); out.append(line)
        return " ".join(out), True, ""      # complete, never truncated


def chunks(text: str, size: int, overlap: int, cap: int) -> list[str]:
    """Split on whitespace boundaries so a segment never starts mid-word."""
    if len(text) <= size:
        return [text]
    out, start = [], 0
    while start < len(text) and len(out) < cap:
        end = min(start + size, len(text))
        if end < len(text):
            cut = text.rfind(" ", start + size - 400, end)
            if cut > start:
                end = cut
        out.append(text[start:end])
        if end >= len(text):
            break
        start = max(end - overlap, start + 1)
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("video_id")
    ap.add_argument("--search-name", required=True)
    ap.add_argument("--candidates", required=True, help="JSON file of identity-resolved experts")
    ap.add_argument("--run-context", default="{}")
    a = ap.parse_args()

    resolved = {k: tunable(k) for k in TUNABLES}
    found, missing = require_tools("yt-dlp")
    if missing:
        sys.exit(f"error: missing required tool(s): {', '.join(missing)}. "
                 f"Install with `uv tool install yt-dlp`. Not an absence of transcripts.")

    timeout = resolved["DBTIPS_KOL_SUBPROCESS_TIMEOUT"]
    meta = fetch_metadata(a.video_id, timeout)
    transcript, available, tool_note = fetch_transcript(a.video_id, timeout)

    # GATE: no transcript, no analysis. A caption fetch that returned nothing is a
    # tool outcome, not a finding about the video -- so this exits 3 (distinct from
    # a real failure) and reports the video as unanalysable rather than emitting a
    # record with a null opinion that downstream cannot tell apart from "no stance".
    if not available:
        # A throttle is not an absence. Exiting with the same code and reason for
        # both would let a rate limit be recorded as "this video has no captions",
        # which is a false finding about the video and unrecoverable downstream.
        throttled = bool(re.search(r"not a bot|Sign in to confirm|429|Too Many Requests|"
                                   r"rate.?limit|temporarily blocked", tool_note or "", re.I))
        print(json.dumps({"records": [], "run": {
            "video_id": a.video_id, "search_name": a.search_name,
            "analysed": False,
            "reason": "throttled" if throttled else "no_transcript",
            "retryable": throttled,
            "note": ("Rate limited by the source after retries. RETRYABLE: re-run this "
                     "video before concluding anything. Lower DBTIPS_KOL_FETCH_WORKERS."
                     if throttled else
                     "No English captions could be fetched. Not classified and not "
                     "extracted; counts toward videos_considered, never toward findings."),
            "tools_found": found, "tools_missing": missing,
            "tunables_resolved": resolved}}, ensure_ascii=False, indent=1))
        return 3

    try:
        from baml_client import b
    except ImportError:
        sys.exit("error: baml_client not found. Run `baml-cli generate` from the directory "
                 "holding baml_src/ — the skill ships BAML source, not the built types.")
    if not os.getenv("GEMINI_API_KEY"):
        sys.exit("error: GEMINI_API_KEY is not set; the extraction client cannot authenticate.")

    ctx = json.loads(a.run_context)
    ctx.update({"tools_found": found, "tools_missing": missing,
                "transcript_available": available, "tunables": resolved})

    segments = chunks(transcript,
                      resolved["DBTIPS_KOL_CHUNK_CHARS"],
                      resolved["DBTIPS_KOL_CHUNK_OVERLAP"],
                      resolved["DBTIPS_KOL_MAX_CHUNKS"])
    ctx["transcript_chars"] = len(transcript)
    ctx["segments"] = len(segments)

    guidelines = GUIDELINES.read_text(encoding="utf-8")
    candidates = Path(a.candidates).read_text(encoding="utf-8")
    meta_json = json.dumps(meta, ensure_ascii=False)

    # Each segment sees what earlier segments established, so a stance developed
    # across a whole talk accumulates instead of being re-derived from a fragment.
    payload: dict = {}
    prior = ""
    for i, seg in enumerate(segments, 1):
        result = b.ExtractKolVideo(
            search_name=a.search_name,
            video_metadata_json=meta_json,
            transcript=seg,
            candidate_experts_json=candidates,
            guidelines=guidelines,
            run_context=json.dumps(ctx, ensure_ascii=False),
            chunk_label=f"{i} of {len(segments)}",
            prior_extraction_json=prior,
        )
        payload = result.model_dump()
        prior = json.dumps({"records": payload.get("records") or []}, ensure_ascii=False)

    payload.setdefault("run", {})["segments_analysed"] = len(segments)
    payload["run"]["transcript_chars"] = len(transcript)

    # `video` is a reserved BAML keyword, so the class declares video_url and
    # aliases it. BAML's @alias reaches the prompt, NOT the generated Pydantic
    # field -- verified against 0.214.0 -- so the rename must happen here or the
    # consumer receives a field it does not read. Also fill the derived URL when
    # the model left it empty: it is a function of video_id, never a judgement.
    for rec in payload.get("records") or []:
        url = rec.pop("video_url", None)
        rec["video"] = url or (f"https://www.youtube.com/watch?v={rec['video_id']}"
                               if rec.get("video_id") else None)
    payload.setdefault("run", {})["tunables_resolved"] = resolved
    print(json.dumps(payload, ensure_ascii=False, indent=1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
