# GENERATED by aganitha-ie-skill-creator. Never hand-edit.
#
# /// script
# requires-python = ">=3.11"
# dependencies = []
#
# Requires yt-dlp on PATH — see SETUP.md.
# ///
"""Types-only path: fetch metadata + transcript for videos, for the AGENT to read.

  uv run tools/transcript.py --videos videos.json --out-dir run/tx [--limit N]

In an agentic harness the agent is already the model — it has the guidelines
loaded. This fetches what it needs to read; the agent extracts, then
tools/validate.py checks the output against the contract. No model is called
here, and no API key is needed.

Emits one JSON per video plus a combined digest. A fetch failure is recorded as
transcript_available=false, never as an empty finding about the video.
"""
from __future__ import annotations

import argparse, concurrent.futures as cf, json, os, random, re, shutil, subprocess, sys, tempfile, time
from pathlib import Path

TUNABLES: dict[str, int] = {
    "DBTIPS_KOL_SUBPROCESS_TIMEOUT": 120,
    # NOT a cap on what is stored. The full transcript is always kept; this is
    # the segment size the extractor chunks it into. Truncating at fetch time
    # silently discards the back half of a long talk, which is where a speaker's
    # argument usually is -- the introduction is at the front.
    "DBTIPS_KOL_CHUNK_CHARS": 24000,
    # Characters repeated between consecutive segments, so a stance that straddles
    # a boundary is not cut in half.
    "DBTIPS_KOL_CHUNK_OVERLAP": 1500,
    "DBTIPS_KOL_DESCRIPTION_CHARS": 4000,
    # Concurrent yt-dlp processes. YouTube throttles aggressively: at 12 workers
    # per run, three concurrent runs put 36 processes against it and 80 of 168
    # videos came back "Sign in to confirm you're not a bot". Keep this low; it
    # is a politeness limit, not a speed dial -- [[respect-source-rate-limits]].
    "DBTIPS_KOL_FETCH_WORKERS": 4,
    # Milliseconds to wait between starting requests, spreading load rather than
    # bursting. Raise if throttling still appears.
    "DBTIPS_KOL_FETCH_DELAY_MS": 400,
    # Attempts per video when YouTube throttles, with exponential backoff.
    "DBTIPS_KOL_THROTTLE_RETRIES": 3,
    "DBTIPS_KOL_THROTTLE_BACKOFF_MS": 5000,
}


def tunable(name: str) -> int:
    raw = os.getenv(name)
    if raw in (None, ""):
        return TUNABLES[name]
    try:
        v = int(raw)
    except ValueError:
        sys.exit(f"error: {name}={raw!r} is not an integer.")
    if v <= 0:
        sys.exit(f"error: {name}={v} must be positive.")
    return v


THROTTLED = re.compile(r"not a bot|Sign in to confirm|HTTP Error 429|Too Many Requests|"
                       r"rate.?limit|temporarily blocked", re.I)


def is_throttled(text: str) -> bool:
    """A throttle and an absence are different states. Conflating them turns a
    rate limit into a false finding that the video has no captions."""
    return bool(text and THROTTLED.search(text))


def _run(cmd: list[str], timeout: int):
    try:
        return subprocess.run(cmd, capture_output=True, text=True, timeout=timeout, check=False)
    except subprocess.TimeoutExpired:
        return None


def vtt_to_text(path: Path) -> str:
    seen, out = set(), []
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = line.strip()
        if not line or "-->" in line or line.startswith(("WEBVTT", "Kind:", "Language:", "NOTE")):
            continue
        line = re.sub(r"<[^>]+>", "", line).strip()
        if line and line not in seen:
            seen.add(line); out.append(line)
    return " ".join(out)          # complete, never truncated


def fetch_one(video_id: str, timeout: int, desc_chars: int) -> dict:
    """Retries only on throttling. A genuinely unavailable video is not retried."""
    attempts = tunable("DBTIPS_KOL_THROTTLE_RETRIES")
    backoff = tunable("DBTIPS_KOL_THROTTLE_BACKOFF_MS") / 1000.0
    time.sleep(random.uniform(0, tunable("DBTIPS_KOL_FETCH_DELAY_MS") / 1000.0))
    for attempt in range(1, attempts + 1):
        rec = _fetch_once(video_id, timeout, desc_chars)
        if not is_throttled(rec.get("tool_error") or ""):
            return rec
        rec["throttled"] = True
        if attempt < attempts:
            time.sleep(backoff * (2 ** (attempt - 1)) + random.uniform(0, 1))
    return rec


def _fetch_once(video_id: str, timeout: int, desc_chars: int) -> dict:
    url = f"https://www.youtube.com/watch?v={video_id}"   # ids starting with '-' parse as flags
    rec: dict = {"video_id": video_id, "transcript_available": False,
                 "metadata_available": False, "transcript": "", "tool_error": None}
    m = _run(["yt-dlp", "--skip-download", "--no-warnings", "--dump-json", url], timeout)
    if m is None:
        rec["tool_error"] = "metadata fetch exceeded DBTIPS_KOL_SUBPROCESS_TIMEOUT"
        return rec
    if m.returncode == 0 and m.stdout.strip():
        d = json.loads(m.stdout.splitlines()[0])
        up = d.get("upload_date") or ""
        rec.update(metadata_available=True,
                   title=d.get("title"),
                   description=(d.get("description") or "")[:desc_chars],
                   channel_name=d.get("channel") or d.get("uploader"),
                   published_date=f"{up[:4]}-{up[4:6]}-{up[6:]}" if len(up) == 8 else None,
                   view_count=str(d["view_count"]) if d.get("view_count") is not None else None,
                   duration_seconds=str(d["duration"]) if d.get("duration") is not None else None)
    else:
        rec["tool_error"] = (m.stderr or "").strip()[:200] or "metadata unavailable"
        return rec
    with tempfile.TemporaryDirectory() as td:
        t = _run(["yt-dlp", "--skip-download", "--write-auto-subs", "--write-subs",
                  "--sub-lang", "en.*", "--sub-format", "vtt", "--no-warnings",
                  "-o", str(Path(td) / "%(id)s.%(ext)s"), url], timeout)
        if t is None:
            rec["tool_error"] = "subtitle fetch exceeded DBTIPS_KOL_SUBPROCESS_TIMEOUT"
            return rec
        vtts = sorted(Path(td).glob("*.vtt"), key=lambda p: "orig" in p.name)
        if vtts:
            rec["transcript"] = vtt_to_text(vtts[0])
            rec["transcript_chars"] = len(rec["transcript"])
            rec["transcript_available"] = bool(rec["transcript"])
    return rec


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--videos", required=True)
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--limit", type=int, default=0)
    a = ap.parse_args()

    if not shutil.which("yt-dlp"):
        sys.exit("error: yt-dlp not on PATH. `uv tool install yt-dlp`. "
                 "A missing tool is not an absence of transcripts.")
    resolved = {k: tunable(k) for k in TUNABLES}
    out_dir = Path(a.out_dir); out_dir.mkdir(parents=True, exist_ok=True)

    pairs = json.loads(Path(a.videos).read_text(encoding="utf-8"))
    order, seen = [], set()
    for p in pairs:                       # preserve discovery order; dedupe videos
        if p["video_id"] not in seen:
            seen.add(p["video_id"]); order.append(p["video_id"])
    if a.limit:
        order = order[:a.limit]

    kols: dict[str, list[str]] = {}
    for p in pairs:
        kols.setdefault(p["video_id"], [])
        if p["kol_name"] not in kols[p["video_id"]]:
            kols[p["video_id"]].append(p["kol_name"])

    results = []
    with cf.ThreadPoolExecutor(max_workers=resolved["DBTIPS_KOL_FETCH_WORKERS"]) as ex:
        futs = {ex.submit(fetch_one, v, resolved["DBTIPS_KOL_SUBPROCESS_TIMEOUT"],
                          resolved["DBTIPS_KOL_DESCRIPTION_CHARS"]): v for v in order}
        for f in cf.as_completed(futs):
            r = f.result()
            r["candidate_kols"] = kols.get(r["video_id"], [])
            (out_dir / f"{r['video_id']}.json").write_text(
                json.dumps(r, ensure_ascii=False, indent=1), encoding="utf-8")
            results.append(r)

    throttled = [r["video_id"] for r in results if r.get("throttled")]
    digest = {"tunables_resolved": resolved,
              "videos_considered": len(order),
              "metadata_ok": sum(r["metadata_available"] for r in results),
              "with_transcript": sum(r["transcript_available"] for r in results),
              "transcript_chars_total": sum(r.get("transcript_chars", 0) for r in results),
              "will_be_chunked": sum(1 for r in results
                                     if r.get("transcript_chars", 0) > resolved["DBTIPS_KOL_CHUNK_CHARS"]),
              # Reported separately and deliberately: a throttled fetch is a tool
              # outcome to retry, NOT evidence the video lacks captions. Treating
              # them as one silently drops videos that do have transcripts.
              "throttled_after_retries": throttled,
              "throttled_count": len(throttled),
              "unavailable": [{"video_id": r["video_id"], "error": r["tool_error"]}
                              for r in results
                              if r["tool_error"] and not r.get("throttled")],
              "tool_errors": [{"video_id": r["video_id"], "error": r["tool_error"]}
                              for r in results if r["tool_error"]]}
    (out_dir / "_digest.json").write_text(json.dumps(digest, ensure_ascii=False, indent=1),
                                          encoding="utf-8")
    print(json.dumps(digest, ensure_ascii=False, indent=1), file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
