# GENERATED by aganitha-ie-skill-creator. Never hand-edit.
#
# /// script
# requires-python = ">=3.11"
# dependencies = ["baml-py>=0.214.0", "pydantic"]
# ///
"""Validate an extraction against the types generated from this project's schema.

    uv run tools/validate.py <extraction.json>

The agent does the extracting — in an agentic harness it is already the model,
with the document read and the guidelines loaded. This checks its output against
the contract, which is the part a model cannot do for itself.

Exits non-zero and prints the field path of every rejection. A malformed
extraction that reports success is the failure the guidelines exist to prevent.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

SKILL_ROOT = Path(__file__).resolve().parent.parent
# baml_client is generated next to baml_src/, which is the skill root — not
# somewhere an isolated interpreter would find it.
sys.path.insert(0, str(SKILL_ROOT))


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    try:
        from baml_client.types import KolVideoExtraction
    except ImportError:
        print("error: baml_client not found. Run `baml-cli generate` from the "
              "directory holding baml_src/ — the skill ships BAML source, not "
              "the built types.", file=sys.stderr)
        return 1
    from pydantic import ValidationError

    payload = json.loads(Path(sys.argv[1]).read_text())
    try:
        KolVideoExtraction(**payload)
    except ValidationError as exc:
        print(f"{len(exc.errors())} rejection(s):", file=sys.stderr)
        for e in exc.errors():
            loc = ".".join(str(x) for x in e["loc"])
            print(f"  {loc}: {e['msg']}", file=sys.stderr)
        return 1
    print("valid")
    return 0


if __name__ == "__main__":
    sys.exit(main())
